### ISSUE TITLE
RecordsInfo.vue producing error

### ISSUE THREAD

**Issue by clnt** [laravel-enso/VueDatatable#81] opened 2018-08-06 16:13 UTC
This is  a **bug**.

### Prerequisites
* [ ✅ ] Are you running the latest version?
* [ ✅ ] Are you reporting to the correct repository?
* [ ✅ ] Did you check the documentation?
* [ ✅ ] Did you perform a cursory search?

### Description
`RecordsInfo.vue` is throwing an error which seems to be coming from the computed properties (see screenshot below of error), all computed properties are showing `(error during evaluation)`. The error goes away if I comment out the contents of the `chunkInfo()` computed property, however the other computed properties still show `(error during evaluation)`. 

![screen shot 2018-08-06 at 12 31 14](https://user-images.githubusercontent.com/19330442/43727476-ff6a08f2-9999-11e8-80c4-0cace2fc133d.png)

It seems to be related to the `this.i18n()` function, when I change the `chunkInfo()` computed property to the following, it produces no error and shows the string on page.

```
        chunkInfo() {
            return 'From' + this.startInfo + ' ' + 'To ' + this.start + this.body.data.length;
        }
```

### Steps to Reproduce
Installed into a Laravel project standalone without the rest of Enso, followed the documentation for an independant installation, all listed dependencies are installed.

The error only happens when data is in the table.

### Expected behavior
A string like shown in the example `From 1 to 10 of 100000 entries (filtered from 100000 total records)`

### Actual behavior
No string generated at all, error in console shown above.

**Comment by aocneanu** [comment] 2018-08-07 08:10
I'm trying to reproduce but I can't. You can to the [table example page](https://www.laravel-enso.com/examples/table) and play around. It's not an Enso environment and all the computed props work well. You have access from the interface to all the code files, maybe you can spot something I missed.

**Comment by aocneanu** [comment] 2018-08-11 05:08
Closing due to inactivity

**Comment by clnt** [comment] 2018-08-15 09:48
@aocneanu Hi mate, sorry I have been busy and not been able to spend time figuring this error out. However, I have just pinpointed my issue to this function default value: 

```
        i18n: {
            type: Function,
            default(key) {
                return Object.keys(this.$options.methods).includes('__')
                    ? this.__(key)
                    : key;
            },
        }
```

If I just `return key` from this, all my errors go away and delete modal works again etc.

How is this localisation supposed to be handled when running this package outside of Enso environment?

**Comment by aocneanu** [comment] 2018-08-16 09:11
`i18n` lets you pass your own localisation function for the vue-table.

If you don't pass such a function, than the default will be used.

In Enso the global localisation helper is `__`. This helper is available on every vue instance.

`Object.keys(this.$options.methods)` returns an array of all the methods available on the table's vue instance, and with `.includes('__')` we are able to identify if there is a matching `__` or not. If we get a match, than the function is used, if not, we return the key.

Try this in your vue dev console while selecting the table component and report back the result

![image](https://user-images.githubusercontent.com/16073274/44199712-7e667e00-a14d-11e8-9fde-4ec3f5d78efa.png)

**Comment by clnt** [comment] 2018-08-16 16:44
@aocneanu 

I've replicated that and I got the same result in my browser console, I think the problem is that methods is undefined when the default value is created? I did this as a test:

```
        i18n: {
            type: Function,
            default(key) {
              console.log(JSON.stringify(this.$options.methods));
              return Object.keys(this.$options.methods).includes('__')
                ? this.__(key)
                : key;
            },
        }
```

The console.log is showing as `undefined`

**Comment by aocneanu** [comment] 2018-08-17 10:12
If you try `console.log(this)` what happens?

**Comment by clnt** [comment] 2018-08-20 09:04
This is the output of `console.log(this)`:

![screen shot 2018-08-20 at 10 00 54](https://user-images.githubusercontent.com/19330442/44331034-6437e300-a460-11e8-9d34-2317ca8d6c1c.png)

**Comment by clnt** [comment] 2018-08-21 13:57
@aocneanu Awesome that has fixed it! Both my RecordsInfo.vue and Modal.vue are now displaying properly and not producing any errors 👍

**Comment by aocneanu** [comment] 2018-08-21 14:02
I will update the repo as well. I will close this when it's done.

**Closed** 2018-08-21 14:33 UTC
