### ISSUE TITLE
Empty or missing relation and null attributes on query

### ISSUE THREAD

**Issue by degustadev** [laravel-enso/VueDatatable#138] opened 2019-03-29 10:35 UTC
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

in UserTable::query Table Builder when I return the following
```php
return User::select('id as dtRowId', 'email')->with('role')->orderBy('id');
```
the generated object is a User model with all attributes set to `NULL` and the relation role is missing, and if I try with any other relation its also empty (both relations and attributes work because I'm using them in other places). I can't find anything similar either in documentation or github issues.

### Steps to Reproduce

1. Define a User Model with any attribute and a relation
2. Try to return in Table Builder this relation or any attribute.

### Expected behavior

I expect the relations and attributes to be filled.

### Actual behavior

Relations are either missing or empty and attributes are `NULL`.

**Comment by aocneanu** [comment] 2019-03-29 11:36
Not a bug, that's how Eloquent is working.

Adding the `id` to the select (besides `dtRowId`)  will solve the relationship problem.

But to take full advantage of the benefits this lib provides (sorting, full search etc) you should change the query to something like [this](https://github.com/laravel-enso/Core/blob/master/src/app/Tables/Builders/UserTable.php)

Make sure you read the docs in detail.

**Comment by degustadev** [comment] 2019-03-29 11:57
Thanks @aocneanu the id fixed it. Such a simple thing..

I can't do it like the example you provided since I'm formatting the data throught attributes.

But if I do it through attributes there's a way to filter them on search? Right now its throwing an error saying can't find "x" column and makes sense since its not a column.

**Comment by aocneanu** [comment] 2019-03-29 12:05
>I can't do it like the example you provided since I'm formatting the data throught attributes.

You're talking about Laravel accessors? If so there is no technical way to filter by them, and you should leave the `"meta": []` empty for those columns.

**Comment by degustadev** [comment] 2019-03-29 12:19
Yes Laravel accessors. Mh then how do you propose to make it work so I can filter by them?

For example this attribute:

```php
public function getMediaNameAttribute()
    {
        if ((!$this->socialMediaProfiles->isEmpty())) {
            return $this->socialMediaProfiles->first()->name;
        }

        return $this->name;
    }
```

Im taking the name of first result of relation socialmediaprofiles, otherwise im returning user name. There's any workaround for this to achieve both things? (The accessor logic and table filter).

**Comment by aocneanu** [comment] 2019-03-29 15:54
Maybe try another database design. But this is not related to this package so I will close this for now.

**Closed by aocneanu** 2019-03-29 15:54 UTC
